require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'FeedbackReporterExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

      pod 'react-native-feedback-reporter', :path => '../..'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # Resolved issue as per: https://github.com/facebook/react-native/issues/30836#issuecomment-772830882
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
